<header>
      <img src="images/Logo2.png" alt="Logo" id="LogoTop" >
      <p>
            <?php echo ($page=="index")?"Welcome to Home Page" : "";
            ?>
            <?php echo ($page=="product")?"Welcome to QT Group Products Page" : "";
            ?>
            <?php echo ($page=="enquiry")?"Welcome to QT Group Enquiry Page" : "";
            ?>
            <?php echo ($page=="payment")?"Welcome to Payment Page" : "";
            ?>
            <?php echo ($page=="about")?"Welcome to QT Group Profile Page" : "";
            ?>
            <?php echo ($page=="enhancements")?"Welcome to Enhancement Page" : "";
            ?>
            <?php echo ($page=="enhancements2")?"Welcome to Enhancement 2 Page" : "";
            ?>
            <?php echo ($page=="enhancements3")?"Welcome to Enhancement 3 Page" : "";
            ?>
            <?php echo ($page=="fix_order")?"Welcome to Fix Order Page" : "";
            ?>
            <?php echo ($page=="manager")?"Welcome to Manager Page" : "";
            ?>
            <?php echo ($page=="receipt")?"Welcome to Receipt Page" : "";
            ?>
      </p>
      
  </header> 