<nav class="MainNav">   
      <a <?php echo ($page=="index")?"class='active'" : "";?> href="index.php">Home</a>
      <a <?php echo ($page=="product")?"class='active'" : "";?>
      href="product.php">Products Description</a>
      <a <?php echo ($page=="enquiry")?"class='active'" : "";?> href="enquire.php">Product Inquiry</a>
      <a <?php echo ($page=="payment")?"class='active'" : "";?> href="payment.php">Payment</a>
      <a <?php echo ($page=="about")?"class='active'" : "";?> href="about.php">About Us</a>
      <a <?php echo ($page=="enhancements")?"class='active'" : "";?> href="enhancements.php">Enhancements</a>
      <a <?php echo ($page=="enhancements2")?"class='active'" : "";?> href="enhancements2.php">Enhancements 2 </a>
</nav>

